name: delete-all
version: 0.0.3
usage: delete and purge all releases
description: |-
  Delete and purge all releases from Kubernetes in one simple command.
useTunnel: true
command: $HELM_PLUGIN_DIR/command.sh
